/* The count-and-say sequence is the sequence of integers with the first five terms as following:

1.     1
2.     11
3.     21
4.     1211
5.     111221
1 is read off as "one 1" or 11.
11 is read off as "two 1s" or 21.
21 is read off as "one 2, then one 1" or 1211.
Given an integer n, generate the nth term of the count-and-say sequence.

Note: Each term of the sequence of integers will be represented as a string.

Example 1:

Input: 1
Output: "1"
Example 2:

Input: 4
Output: "1211" 
*/

/* I figured it out:

You start with "1" as the first line.

Each subsequent line (n) is generated by passing the line before it (n - 1) as an input to a somewhat unusual function (I'll explain as brute-force for illustrative purposes):

Loop through the line (n - 1) as a string. For a given character, count how many consecutive times it repeats, then put that on line n followed by the number.

For example:

If you have "1", the next line is "11".
If you have "11", the next line is "21".
If you have "111", the next line is "31".
If you have "1111", the next line is "41".
See the basic pattern? Just do that for every set of repeating characters on the previous line.
Here's what it looks like with more than one sequence:

If you have "11222", the next line is "2132" ("11" becomes "21" and "222" becomes "32").
If you have "112225", the next line is "213215" ("11" becomes "21", "222" becomes "32", and "5" becomes "15").
*/

class Solution {
    public String countAndSay(int n) {
        String s = "";
        while (n-- > 0) {
            s = count(s);
        }

        return s;
    }

    private String count(String s) {

        if (s.equals(""))
            return "1";

        s = s + "?"; // ?: placeholder to prevent index out of bound exception
        int count = 1;
        StringBuilder ans = new StringBuilder("");
        for (int i = 0; i < s.length() - 1; i++) {
            if (s.charAt(i) == s.charAt(i + 1)) {
                count++;
            } else {
                ans.append(count);
                ans.append(s.charAt(i));
                count = 1;
            }
        }

        return ans.toString();
    }
}